In [ ]:
##### 망고플레이트 성수지역 메인페이지 크롤링하기 #####

In [ ]:
import requests
import pandas as pd
import pandas as pd 
from bs4 import BeautifulSoup

### 1. 변수 설정
address = u"https://www.mangoplate.com/search/성수" 
df_list = [] #담을 변수 배열  


#url parameters 
values = {
    "keyword" : u"성수",
    'page' : 0
}

#custom header for crawling 
custom_header = {
    'referer' : 'https://www.mangoplate.com',
    'user-agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36' 
}

In [37]:

### 2. 크롤링
# 10페이지(max)까지 메인 페이지 크롤링하기 
for page in range(1,11):
    values["page"] = page #각 페이지에 대해 수행
    params = parse.urlencode(values) #url 형식에 맞게 encoding
    url = (address + "?" + params) #url 합치기
    r = requests.get(url, params = values, headers = custom_header) #컨텐츠 불러오기
    soup = BeautifulSoup(r.text, 'html.parser') # html형태로 저장 후 예쁘게 만들기
    
    #원하는 정보만 추출하여 변수 저장
    line = 0
    for li in soup.select("figcaption > div"):
        try:
            name = li.select_one('h2.title').text
            rating = li.select_one('strong.point').text
            view = li.select_one('span.view_count').text
            review_cnt = li.select_one('span.review_count').text
            
            #dataframe으로 만들땐 반드시 딕셔너리로 저장 후 삽입
            temp_row = {
                'name' : name,
                'rating' : rating,
                'view' : view,
                'review_count' : review_cnt,
            }
            df_list.append(temp_row)
            
            line += 1
            print("row "+ str(line) + " completed")
            
            #problem : line이 selector 끝에 닿으면 안멈춤. why?
            if line == 20:
                break
            
        except BaseException as ex:
            print(ex)

    print("-------page : "+ str(page) + "-------")
    

#soup = soup.prettify() #보기 예쁘게 만들어주쎄욘 
#print(soup)

row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 1-------
row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 2-------
row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 3-------
row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 4-------
row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 5-------
row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 6-------
row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 7-------
row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 8-------
row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 9-------
row 1 completed
row 2 completed
row 3 completed
row 4 completed
row 5 completed
row 6 completed
row 7 completed
row 8 completed
row 9 completed
row 10 completed
row 11 completed
row 12 completed
row 13 completed
row 14 completed
row 15 completed
row 16 completed
row 17 completed
row 18 completed
row 19 completed
row 20 completed
-------page : 10-------

In [40]:
mango_df = pd.DataFrame(df_list)
mango_df.head(10)

,name,rating,view,review_count
0,바위파스타바\n,4.8,"106,170",37
1,쿠나\n,4.8,"24,060",20
2,보이어\n,4.7,"97,111",48
3,Ndd\n,4.7,"15,435",28
4,세스크멘슬\n,4.6,"60,801",51
5,마하차이\n,4.6,"68,200",54
6,다로베\n (서울숲점)\n,4.5,"257,505",231
7,와하카\n,4.5,"179,769",128
8,맛차차\n,4.5,"43,559",37
9,팩피\n,4.4,"264,695",133

In [44]:
#encoding tip 
##한글 변수가 포함될땐 반드시 유니코드로 작성해야함 
# 참고 : https://ifyourfriendishacker.tistory.com/5
abc = u"안녕"
print(abc)
encoded_abc = abc.encode('utf-8')
abc.encode('utf-8')
encoded_abc.decode('utf-8')

안녕

'안녕'